export enum ACTION_TYPE {
    ADD = 'ADD',
    ADD_COMMENT = 'ADD_COMMENT',
    ADD_COMMENTS = 'ADD_COMMENTS',
    ADD_DISHES = 'ADD_DISHES',
    ADD_LEADERS = 'ADD_LEADERS',
    ADD_PROMOTIONS = 'ADD_PROMOTIONS',

    FAILED = 'FAILED',
    FAILED_COMMENTS = 'FAILED_COMMENTS',
    FAILED_DISHES = 'FAILED_DISHES',
    FAILED_LEADERS = 'FAILED_LEADERS',
    FAILED_PROMOTIONS = 'FAILED_PROMOTIONS',

    LOADING = 'LOADING',
    LOADING_COMMENTS = 'LOADING_COMMENTS',
    LOADING_DISHES = 'LOADING_DISHES',
    LOADING_LEADERS = 'LOADING_LEADERS',
    LOADING_PROMOTIONS = 'LOADING_PROMOTIONS',
}
