export enum ACTION_TYPE {
    ADD_COMMENT = 'ADD_COMMENT',
    ADD_COMMENTS = 'ADD_COMMENTS',
    ADD_DISHES = 'ADD_DISHES',
    ADD_PROMOTIONS = 'ADD_PROMOS',

    COMMENTS_FAILED = 'COMMENTS_FAILED',
    DISHES_FAILED = 'DISHES_FAILED',
    PROMOTIONS_FAILED = 'PROMOS_FAILED',

    COMMENTS_LOADING = 'COMMENTS_LOADING',
    DISHES_LOADING = 'DISHES_LOADING',
    PROMOTIONS_LOADING = 'PROMOS_LOADING',
}
